version: "3.6"

services:
  sut:
    image: damiantroy/radarr:${CACHE_TAG}
    volumes:
      - radarr_config:/config
    command: >
      bash -c "/usr/bin/mono --debug /opt/Radarr/Radarr.exe -nobrowser &
               test.sh -t 30 -u http://localhost:7878/ -e Radarr"

volumes:
  radarr_config:
    driver_opts:
      type: tmpfs
      device: tmpfs
