version: "3.6"

services:
  sut:
    build: .
    volumes:
      - radarr_config:/config
    command: >
      bash -c "/opt/Radarr/Radarr -nobrowser -data=/config &
               test.sh -t 30 -u http://localhost:7878/ -e Radarr"

volumes:
  radarr_config:
    driver_opts:
      type: tmpfs
      device: tmpfs
